export const schemas = {
  products: [
    { label: "Product ID", value: "productid", type: "number" },
    { label: "Name", value: "productname", type: "string" },
    { label: "Supplier ID", value: "supplierid", type: "number" },
    { label: "Category ID", value: "categoryid", type: "number" },
    { label: "Quantity per Unit", value: "quantityperunit", type: "string" },
    { label: "Unit Price", value: "unitprice", type: "number" },
    { label: "Units in Stock", value: "unitsinstock", type: "number" },
    { label: "Units on Order", value: "unitsonorder", type: "number" },
    { label: "Reorder level", value: "reorderlevel", type: "number" },
    { label: "Discontinued", value: "discontinued", type: "number" },
  ],
  customers: [
    { label: "Customer ID", value: "customerid", type: "string" },
    { label: "Company Name", value: "companyname", type: "string" },
    { label: "Contact Name", value: "contactname", type: "string" },
    { label: "Contact Title", value: "contacttitle", type: "string" },
    { label: "Address", value: "address", type: "string" },
    { label: "City", value: "city", type: "string" },
    { label: "Region", value: "region", type: "string" },
    { label: "Name", value: "name", type: "string" },
    { label: "Postal Code", value: "postalcode", type: "number" },
    { label: "Country", value: "country", type: "string" },
    { label: "Phone", value: "phone", type: "string" },
    { label: "Fax", value: "fax", type: "string" },
  ],
  orders: [
    { label: "Order ID", value: "orderid", type: "string" },
    { label: "Customer ID", value: "customerid", type: "string" },
    { label: "Employee ID", value: "employeeid", type: "number" },
    { label: "Order Date", value: "orderdate", type: "date" },
    { label: "Required Date", value: "requireddate", type: "date" },
    { label: "Shipped Date", value: "shippeddate", type: "date" },
    { label: "Shipped Via", value: "shipvia", type: "number" },
    { label: "Freight", value: "freight", type: "number" },
    { label: "Ship Name", value: "shipname", type: "string" },
    { label: "Ship Address", value: "shipaddress", type: "string" },
    { label: "Ship City", value: "shipcity", type: "string" },
    { label: "Ship Region", value: "shipregion", type: "string" },
    { label: "Ship Postal Code", value: "shippostalcode", type: "number" },
    { label: "Ship Country", value: "shipcountry", type: "string" },
  ],
};
